### ISSUE TITLE
The moveAssets transform has been removed.

### ISSUE THREAD

**Issue by rustyconover** [papandreou/bringhome#86]
Reading this code to trace through an example to the discovery, it is likely this commit:

https://github.com/assetgraph/assetgraph/commit/f2d1d720e1e52258c4ac4e307d6dab04284619a8

Broke the code of this tool since those transforms are no longer available in the assetgraph core.

**Comment by papandreou** [comment]
Yeah, that was intentional, on assetgraph master we're cooking up a bunch of breaking changes in an effort to plugin-ify the whole thing more. This will take a while to complete. It'll be some work in these downstream tools to adapt to that. In the mean time you should probably stick to [v6](https://github.com/assetgraph/assetgraph/tree/v6). I've just backported that `javascript:` fix and released assetgraph 6.4.1

Btw. parts of `moveAssets` ended up in https://github.com/assetgraph/assetgraph-hashfiles
